version: 0.2

env:
  variables:
    DOCKER_USERNAME: "nusanj"
    IMAGE_NAME: "MyMavenApp"
    IMAGE_TAG: "v1"
  

phases:
  pre_build:
    commands:
      - echo logging in to Docker hub
      - docker login -u $DOCKER_USERNAME -p Nuribaba@123
  build: 
    commands:
      - echo build started on 'date'
      - echo Building docker image...
      - docker build -t $IMAGE_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_NAME:$IMAGE_TAG $DOCKER_USERNAME/$IMAGE_NAME:$IMAGE_TAG

  post-build:
    commands:
      - echo build complete 'date'
      - echo pushing docker image...
      - docker push $DOCKER_USERNAME/$IMAGE_NAME:$IMAGE_TAG
