version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  pre_build:
    commands:
      - echo "Starting build..."
      - mvn clean
  build:
    commands:
      - mvn package
  post_build:
    commands:
      - echo "Build completed on `date`"
      - aws s3 cp target/MyMavenApp.jar s3://sanjaya-codebuild/Mypath/

artifacts:
  files:
    - target/myapp.jar
